'use strict';

(function () {
  var PIN_LOCATION_LEFT_MIN = 40;
  var PIN_LOCATION_LEFT_MAX = 1160;
  var PIN_LOCATION_TOP_MIN = 130;
  var PIN_LOCATION_TOP_MAX = 630;
  var MAIN_PIN_CIRCLE_DIAMETER = 62;
  var MAIN_PIN_SIZE_POINT_HEIGHT = 20;
  var xhrStatusSuccess = 200;

  window.data = {
    PIN_LOCATION_LEFT_MIN: PIN_LOCATION_LEFT_MIN,
    PIN_LOCATION_LEFT_MAX: PIN_LOCATION_LEFT_MAX,
    PIN_LOCATION_TOP_MIN: PIN_LOCATION_TOP_MIN,
    PIN_LOCATION_TOP_MAX: PIN_LOCATION_TOP_MAX,
    MAIN_PIN_CIRCLE_DIAMETER: MAIN_PIN_CIRCLE_DIAMETER,
    MAIN_PIN_SIZE_POINT_HEIGHT: MAIN_PIN_SIZE_POINT_HEIGHT,
    xhrStatusSuccess: xhrStatusSuccess
  };
})();
